apiVersion: apps/v1
kind: Deployment
metadata:
  name:  idbi-efk-kibana
  namespace: idbi-efk
  labels:
    component: kibana
spec:
  replicas: 2
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: efk-node
              operator: In
              values:
              - efk

      tolerations:
      - key: "node-role.kubernetes.io/efk_elasticsearch"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: kibana
        image: 10.143.140.124:5010/kibana-oss:7.7.1
        env:
        - name: "CLUSTER_NAME"
          value: "SAG_EventDataStore"
        - name: ELASTICSEARCH_URL
          value: 'http://idbi-efk-es-svc-h.idbi-efk.svc.cluster.local:9200'
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          #name: kibana
          protocol: TCP
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /api/status
            port: 5601
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /api/status
            port: 5601
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: kibana-config
          mountPath: /tmp/kibana.yml
          subPath: kibana.yml
          readOnly: false
        command:
        - /bin/bash
        - -c
        - |
         cp /tmp/kibana.yml /usr/share/kibana/config/kibana.yml
         /usr/share/kibana/bin/kibana
      volumes:
      - name: kibana-config
        configMap:
          name: idbi-efk-kibana-config
          items:
          - key: kibana.yml
            path: kibana.yml
          defaultMode: 0777

