apiVersion: v1
kind: Service
metadata:
  name: idbi-efk-kibana-svc
  namespace: idbi-efk
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP

