apiVersion: v1
kind: ConfigMap
metadata:
  name: idbi-apim-is-config
  namespace: nsp-idbi-apim-uat
data:

  application.properties: |
    #Sample Generated Template
    #Fri Oct 08 14:42:43 IST 2021
    jdbc.MWSUser.dbURL=jdbc\:wm\:oracle\://dcoradbnpscan.idbibank.com\:15210;serviceName\=APIMUATSRV
    jdbc.MWSUser.password={AES}2txKs7gKqS5e4YKVYRyCFA==
    jdbc.MWSUser.userid=mwsuat
    jdbc.ISInternal.dbURL=jdbc\:wm\:oracle\://dcoradbnpscan.idbibank.com\:15210;serviceName\=APIMUATSRV
    jdbc.ISInternal.password={AES}FClVSJyzNqtdcSQFX7F2Uw==
    jdbc.ISInternal.userid=isuat
    settings.watt.server.cluster.aware=true
    settings.watt.server.cluster.name=IS_TSA_Cluster
    settings.watt.server.cluster.tsaURLs=idbi-apim-tsa-cluster-0.idbi-apim-tsa-svc-h.nsp-idbi-apim-uat.svc.cluster.local\:9510,idbi-apim-tsa-cluster-1.idbi-apim-tsa-svc-h.nsp-idbi-apim-uat.svc.cluster.local\:9510
    settings.watt.server.compile=/opt/softwareag/jvm/jvm/bin/javac -classpath {0} -d {1} {2}
    settings.watt.server.auth.samlResolver=https://idbi-apim-mws-svc-h.nsp-idbi-apim-uat.svc.cluster.local:8585/services/SAML
    settings.watt.server.threadPool=1000
    settings.watt.net.jsse.client.disabledProtocols=SSLv2Hello,SSLv3,TLSv1,TLSv1.1
    settings.watt.net.jsse.server.disabledProtocols=SSLv2Hello,SSLv3,TLSv1,TLSv1.1
    user.Administrator.password={AES}/Rr3q6B6LfFEOShP9FJ0jUwbvqGC7rAKwvzC3kkMgEg=
    user.Developer.password={AES}/Rr3q6B6LfFEOShP9FJ0jUwbvqGC7rAKwvzC3kkMgEg=
    user.Replicator.password={AES}/Rr3q6B6LfFEOShP9FJ0jUwbvqGC7rAKwvzC3kkMgEg=
    truststore.DEFAULT_JVM_TRUSTSTORE.ksLocation=/opt/softwareag/jvm/jvm/jre/lib/security/cacerts
    truststore.DEFAULT_JVM_TRUSTSTORE.ksPassword={AES}z/+xVlzI9T/Dfo7Su4lrCQ==
    truststore.istruststore.ksLocation=/opt/softwareag/common/conf/truststore.jks
    truststore.istruststore.ksPassword={AES}O1e2whkLOxlv+xDIMJZgBR/jpQWQJz0gfdRTe9QUnPE=
    keystore.iskeystore.keyAlias.idbibank.keyAliasPassword={AES}KWbniYeILIJ4Cphs7Tdm91kTBR6t5rVRVLZ0cyiJ20U=
    keystore.iskeystore.ksLocation=/opt/softwareag/common/conf/keystore.jks
    keystore.iskeystore.ksPassword={AES}KWbniYeILIJ4Cphs7Tdm91kTBR6t5rVRVLZ0cyiJ20U=

  custom_wrapper.conf: |
    #encoding=UTF-8
    wrapper.app.parameter.2=4
    wrapper.app.parameter.5=-service
    wrapper.app.parameter.6=sagis107
    wrapper.java.additional.100=-server
    wrapper.java.additional.101=-Dorg.apache.xml.dtm.DTMManager=org.apache.xml.dtm.ref.DTMManagerDefault
    wrapper.java.additional.102=-Djavax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom=com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl
    wrapper.java.additional.103=-Dcom.webmethods.sc.auditing.Use80TableFormat=true
    wrapper.java.additional.104=-Dsun.lang.ClassLoader.allowArraySyntax=true
    wrapper.java.additional.105=-XX:+UseOpenJSSE
    wrapper.java.additional.201=-DWM_HOME=/opt/softwareag
    wrapper.java.additional.202=-Dwatt.server.prepend.classes=/opt/softwareag/common/lib/wm-converters.jar
    wrapper.java.additional.203=-Dwatt.server.append.classes=
    wrapper.java.additional.204=-Dlog4j.configurationFile="/opt/softwareag/profiles/IS_default/configuration/logging/log4j2.properties,.tc.custom.log4j2.properties"
    wrapper.java.additional.204.stripquotes=TRUE
    wrapper.java.additional.301=-Dorg.tanukisoftware.wrapper.WrapperStartStopApp.passthroughMode=START
    wrapper.java.additional.302=-Djava.awt.headless=true
    wrapper.java.additional.303=-DLog4jContextSelector=org.apache.logging.log4j.core.selector.BasicContextSelector
    wrapper.java.classpath.3=/opt/softwareag/common/lib/wm-converters.jar
    wrapper.java.initmemory=4096
    wrapper.java.library.path.11=/opt/softwareag/IntegrationServer/instances/default/lib
    wrapper.java.library.path.append_system_path=TRUE
    wrapper.java.maxmemory=4096
    wrapper.jvm_exit.timeout=300
    wrapper.on_exit.42=RESTART
    wrapper.ping.timeout=300
    wrapper.restart.reload_configuration=TRUE
    wrapper.shutdown.timeout=300
    wrapper.single_invocation=TRUE
    wrapper.working.dir=/opt/softwareag/IntegrationServer/instances/default
    wrapper.java.additional.106=-Djava.security.properties=config/security/webm_override_java.security

  jndi_DEFAULT_IS_JNDI_PROVIDER.properties: |
    #JNDI properties for DEFAULT_IS_JNDI_PROVIDER
    #Thu Oct 28 15:19:12 UTC 2021
    is.jndiAlias.description=system generated JNDI provider alias
    keyAlias=idbibank
    java.naming.factory.initial=com.pcbsys.nirvana.nSpace.NirvanaContextFactory
    keyStorePwdProp=nirvana.ssl.keystore.pass
    trustStoreAlias=istruststore
    trustStoreProp=nirvana.ssl.truststore.path
    trustStorePwdProp=nirvana.ssl.truststore.pass
    keyStoreAlias=iskeystore
    privateKeyProp=nirvana.ssl.keystore.cert
    java.naming.provider.url=nsps\://idbi-um-svc.nsp-idbi-apim-uat.svc.cluster.local\:9002
    keyStoreProp=nirvana.ssl.keystore.path

  messaging.cnf: |
    <?xml version="1.0" encoding="UTF-8"?>

    <IDataXMLCoder version="1.0">
      <record javaclass="com.wm.data.ISMemDataImpl">
        <array name="Configuration" type="record" depth="1">
          <record javaclass="com.wm.data.ISMemDataImpl">
            <value name="aliasName">IS_UM_CONNECTION</value>
            <value name="description">system generated Universal Messaging connection alias</value>
            <value name="CLIENTPREFIX">is</value>
            <null name="user"/>
            <value name="enabled">true</value>
            <value name="csqSize">-1</value>
            <value name="csqDrainInOrder">true</value>
            <value name="type">UM</value>
            <value name="aliasTypeDisplay">Universal Messaging</value>
            <value name="transactionType">NONE</value>
            <value name="systemGenerated">false</value>
            <jboolean name="isClientPrefixShared">true</jboolean>
            <value name="useCSQ">true</value>
            <value name="_state">STARTED</value>
            <value name="um_rname">nsps://idbi-um-svc.nsp-idbi-apim-uat.svc.cluster.local:9002</value>
            <value name="um_tryAgainMaxAttempts">5</value>
            <value name="um_publishWaitTime">30000</value>
            <jboolean name="um_followTheMasterForPublish">true</jboolean>
            <jboolean name="um_followTheMasterForSubscribe">true</jboolean>
            <number name="um_loggingOutput" type="java.lang.Integer">0</number>
            <jboolean name="um_producerMessageTracking">false</jboolean>
            <jboolean name="um_consumerMessageTracking">false</jboolean>
            <value name="um_producerIncludedStrings"></value>
            <value name="um_consumerIncludedStrings"></value>
            <jboolean name="enableRequestReply">true</jboolean>
            <value name="clientAuthType">ssl</value>
            <value name="trustStoreAlias">istruststore</value>
            <value name="keyStoreAlias">iskeystore</value>
            <value name="keyAlias">idbibank</value>
          </record>
          <record javaclass="com.wm.data.ISMemDataImpl">
            <value name="aliasName">IS_DES_CONNECTION</value>
            <value name="description">system generated Digital Event Services connection alias</value>
            <value name="CLIENTPREFIX">IS_DES</value>
            <null name="user"/>
            <value name="enabled">true</value>
            <value name="csqSize">-1</value>
            <value name="csqDrainInOrder">false</value>
            <value name="type">DES</value>
            <value name="aliasTypeDisplay">Digital Event Services</value>
            <value name="transactionType">NONE</value>
            <value name="systemGenerated">false</value>
            <jboolean name="isClientPrefixShared">true</jboolean>
            <value name="useCSQ">false</value>
            <value name="_state">STARTED</value>
          </record>
          <record javaclass="com.wm.data.ISMemDataImpl">
            <value name="aliasName">IS_LOCAL_CONNECTION</value>
            <value name="description">system generated local connection alias</value>
            <value name="enabled">true</value>
            <value name="type">LOCAL</value>
            <value name="aliasTypeDisplay">Local</value>
            <value name="systemGenerated">true</value>
          </record>
        </array>
        <value name="defaultAlias">IS_UM_CONNECTION</value>
      </record>
    </IDataXMLCoder>

  jms.cnf: |
    <?xml version="1.0" encoding="UTF-8"?>

    <IDataXMLCoder version="1.0">
      <record javaclass="com.wm.data.ISMemDataImpl">
        <array name="JMSConfiguration" type="record" depth="1">
          <record javaclass="com.wm.data.ISMemDataImpl">
            <value name="aliasName">DEFAULT_IS_JMS_CONNECTION</value>
            <value name="description">system generated JMS connection alias</value>
            <value name="clientID">IS_JMS_CLIENT</value>
            <null name="user"/>
            <value name="handle">wm.is.admin.jmsConnectionAlias.DEFAULT_IS_JMS_CONNECTION</value>
            <value name="classLoader">INTEGRATION_SERVER</value>
            <value name="enabled">true</value>
            <value name="csqSize">-1</value>
            <value name="csqDrainInOrder">true</value>
            <value name="optTempQueueCreate">true</value>
            <value name="transactionType">0</value>
            <value name="systemGenerated">false</value>
            <value name="manageDestinations">true</value>
            <value name="allowNewConnectionPerTrigger">false</value>
            <value name="producerCachingMode">0</value>
            <value name="producerSessionPoolSize">0</value>
            <value name="producerSessionPoolMinSize">0</value>
            <value name="cacheProducersPoolSize">0</value>
            <value name="cacheProducersPoolMinSize">0</value>
            <value name="cacheProducersQueueList"></value>
            <value name="cacheProducersTopicList"></value>
            <number name="poolTimeout" type="java.lang.Integer">60000</number>
            <number name="producerMaxRetryAttempts" type="java.lang.Long">0</number>
            <number name="producerRetryInterval" type="java.lang.Long">0</number>
            <jboolean name="allowReplyToConsumer">false</jboolean>
            <value name="associationType">0</value>
            <value name="jndi_jndiAliasName">DEFAULT_IS_JNDI_PROVIDER</value>
            <value name="jndi_connectionFactoryLookupName">local_um</value>
            <value name="jndi_connectionFactoryUpdateType">NONE</value>
            <number name="jndi_connectionFactoryPollingInterval" type="java.lang.Integer">0</number>
            <jboolean name="jndi_enableFollowTheMaster">true</jboolean>
            <jboolean name="jndi_automaticallyCreateUMAdminObjects">false</jboolean>
            <number name="um_loggingOutput" type="java.lang.Integer">0</number>
            <jboolean name="um_producerMessageTracking">false</jboolean>
            <jboolean name="um_consumerMessageTracking">false</jboolean>
            <null name="um_producerIncludedStrings"/>
            <null name="um_consumerIncludedStrings"/>
            <value name="providerName">Universal Messaging</value>
            <value name="providerVersion">10.7.0 Build 140269 July 16 2021</value>
            <number name="providerMajorVersion" type="java.lang.Integer">10</number>
            <number name="providerMinorVersion" type="java.lang.Integer">7</number>
          </record>
          <record javaclass="com.wm.data.ISMemDataImpl">
            <value name="aliasName">PE_NONTRANSACTIONAL_ALIAS</value>
            <value name="description">system generated JMS connection alias</value>
            <value name="clientID">IS_PE</value>
            <value name="user"></value>
            <value name="handle">wm.is.admin.jmsConnectionAlias.PE_NONTRANSACTIONAL_ALIAS</value>
            <value name="classLoader">INTEGRATION_SERVER</value>
            <value name="enabled">true</value>
            <value name="csqSize">-1</value>
            <value name="csqDrainInOrder">true</value>
            <value name="optTempQueueCreate">true</value>
            <value name="transactionType">0</value>
            <value name="systemGenerated">false</value>
            <value name="manageDestinations">true</value>
            <value name="allowNewConnectionPerTrigger">false</value>
            <value name="producerCachingMode">0</value>
            <value name="producerSessionPoolSize">0</value>
            <value name="producerSessionPoolMinSize">0</value>
            <value name="cacheProducersPoolSize">0</value>
            <value name="cacheProducersPoolMinSize">0</value>
            <value name="cacheProducersQueueList"></value>
            <value name="cacheProducersTopicList"></value>
            <number name="poolTimeout" type="java.lang.Integer">60000</number>
            <number name="producerMaxRetryAttempts" type="java.lang.Long">0</number>
            <number name="producerRetryInterval" type="java.lang.Long">0</number>
            <jboolean name="allowReplyToConsumer">false</jboolean>
            <value name="associationType">0</value>
            <value name="jndi_jndiAliasName">DEFAULT_IS_JNDI_PROVIDER</value>
            <value name="jndi_connectionFactoryLookupName">local_um</value>
            <value name="jndi_connectionFactoryUpdateType">NONE</value>
            <number name="jndi_connectionFactoryPollingInterval" type="java.lang.Integer">0</number>
            <jboolean name="jndi_enableFollowTheMaster">true</jboolean>
            <jboolean name="jndi_automaticallyCreateUMAdminObjects">false</jboolean>
            <number name="um_loggingOutput" type="java.lang.Integer">0</number>
            <jboolean name="um_producerMessageTracking">false</jboolean>
            <jboolean name="um_consumerMessageTracking">false</jboolean>
            <value name="um_producerIncludedStrings"></value>
            <value name="um_consumerIncludedStrings"></value>
            <value name="providerName">Universal Messaging</value>
            <value name="providerVersion">10.7.0 Build 140269 July 16 2021</value>
            <number name="providerMajorVersion" type="java.lang.Integer">10</number>
            <number name="providerMinorVersion" type="java.lang.Integer">7</number>
          </record>
        </array>
      </record>
    </IDataXMLCoder>
