apiVersion: batch/v1
kind: Job
metadata:
  name: idbi-apim-dbc-job
  namespace: nsp-idbi-apim-uat
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      affinity:
      #   # Pods will be placed in the worker node that has the label dbc-node=dbc
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
             - key: mws-node-uat
               operator: In
               values:
               - mws
      # # Toleration condition for Pods when the node is tainted and the subsequent effect
      tolerations:
      - key: "node-role.kubernetes.io/mws-uat"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - image: 10.143.140.124:5010/apim-sag-dbc:v1.1
        name: idbi-apim-dbc-job
        env:
        - name: DB_APIGW_USER
          valueFrom:
            secretKeyRef: 
              name: idbi-apim-dbc-secret
              key: DB_APIGW_USER
        - name: DB_APIGW_PASSWORD
          valueFrom:
            secretKeyRef: 
              name:  idbi-apim-dbc-secret
              key: DB_APIGW_PASSWORD
        - name: DB_IS_USER
          valueFrom:
            secretKeyRef: 
              name: idbi-apim-dbc-secret
              key: DB_IS_USER
        - name: DB_IS_PASSWORD
          valueFrom:
            secretKeyRef: 
              name:  idbi-apim-dbc-secret
              key: DB_IS_PASSWORD
        - name: DB_MWS_USER
          valueFrom:
            secretKeyRef: 
              name: idbi-apim-dbc-secret
              key: DB_MWS_USER
        - name: DB_MWS_PASSWORD
          valueFrom:
            secretKeyRef: 
              name:  idbi-apim-dbc-secret
              key: DB_MWS_PASSWORD
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef: 
              name:  idbi-apim-dbc-config
              key: DB_TYPE        
        - name: DB_URL
          valueFrom:
            configMapKeyRef: 
              name:  idbi-apim-dbc-config
              key: DB_URL
        command: 
        - /bin/bash
        - -c 
        - |
         /opt/softwareag/common/db/bin/dbConfigurator.sh -a create -pr MWS -v latest -d $(DB_TYPE) -l '$(DB_URL)' -u '$(DB_MWS_USER)' -p '$(DB_MWS_PASSWORD)' -tsdata 'WEBMDATA' -tsindex 'WEBMINDX'
         /opt/softwareag/common/db/bin/dbConfigurator.sh -a create -pr IntegrationServer -v latest -d $(DB_TYPE) -l '$(DB_URL)' -u '$(DB_IS_USER)' -p '$(DB_IS_PASSWORD)' -tsdata 'WEBMDATA' -tsindex 'WEBMINDX'
         /opt/softwareag/common/db/bin/dbConfigurator.sh -a create -pr IntegrationServer -v latest -d $(DB_TYPE) -l '$(DB_URL)' -u  '$(DB_APIGW_USER)' -p '$(DB_APIGW_PASSWORD)' -tsdata 'WEBMDATA' -tsindex 'WEBMINDX'
      # imagePullSecrets:
      # - name: dockerrepocred


