#Separate for each type
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: idbi-apim-um-deploy
  labels:
    app: idbi-apim-um-deploy
  namespace: nsp-idbi-apim-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idbi-apim-um-deploy
  template:
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
      # Pods will be placed in the worker node that has the label terracotta-node=terracotta
        nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: webmethod_messaging-node-uat
                 operator: In
                 values:
                   - webmethod_messaging
      # Toleration condition for Pods when the node is tainted and the subsequent effect
      tolerations:
       - key: "node-role.kubernetes.io/webmethod_messaging-uat"
         operator: "Exists"
         effect: "NoSchedule"
      containers:
      -  name: um-server-container
         image: 10.143.140.124:5010/apim-sag-um:v1.1
         volumeMounts:
            # Path for the container file system running inside pod. 
         -  name: um-license
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/licence.xml
            subPath: licence.xml
            readOnly: false
         -  name: um-server-config
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/bin/Server_Common.conf
            subPath: Server_Common.conf
            readOnly: false
         -  name: um-default-keystore
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/bin/keystore.jks
            subPath: keystore.jks
            readOnly: false
         -  name: um-default-truststore
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/bin/truststore.jks
            subPath: truststore.jks
            readOnly: false
         -  name: data-directory
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/data
            readOnly: false
         ports:
         -  name: nsp 
            containerPort: 9000
         -  name: nsps 
            containerPort: 9002
         readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 60
         livenessProbe: 
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 60
      volumes:
      -  name: um-license 
         configMap:
          name: idbi-apim-um-license-config
          items:
            - key: license-um.xml
              path: licence.xml
          defaultMode: 0777
      -  name: um-server-config
         configMap:
          name: idbi-apim-um-server-config
          items:
            - key: Server_Common.conf
              path: Server_Common.conf
          defaultMode: 0777      
      -  name: um-default-keystore
         configMap:
          name: idbi-apim-default-keystore-config
          items:
            - key: keystore.jks
              path: keystore.jks
          defaultMode: 0777      
      -  name: um-default-truststore
         configMap:
          name: idbi-apim-default-truststore-config
          items:
            - key: truststore.jks
              path: truststore.jks
          defaultMode: 0777      
      -  name: data-directory
         persistentVolumeClaim:
            claimName: idbi-um-pvc
        #  hostPath: 
        #   path: /data/um/data
        #   type: DirectoryOrCreate
    metadata:
      labels:
        app: idbi-apim-um-deploy
