apiVersion: apps/v1
kind: Deployment
metadata: 
  name: idbi-apim-msr2-deploy
  labels:
    app: idbi-apim-msr2-deploy
  namespace: nsp-idbi-apim-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idbi-apim-msr2
  template:
    metadata:
      labels:
        app: idbi-apim-msr2
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
      # Pods will be placed in the worker node that has the label terracotta-node=terracotta
        nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: webmethod_integration_common2-node-uat
                 operator: In
                 values:
                   - webmethod_integration_common2
      # Pods will label app=idbi-apim-tsa-cluster will not be placed together
        podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                 - key: app
                   operator: In
                   values:
                     - idbi-apim-msr2
               topologyKey: "kubernetes.io/hostname"

      # Toleration condition for Pods when the node is tainted and the subsequent effect
      tolerations:
       - key: "node-role.kubernetes.io/webmethod_integration_is-uat"
         operator: "Exists"
         effect: "NoSchedule"
       - key: "node-role.kubernetes.io/webmethod_messaging-uat"
         operator: "Exists"
         effect: "NoSchedule"
      containers:
      - name: idbi-apim-msr2
        image: 10.143.140.124:5010/apim-sag-ismsr2:v1.1
        # imagePullPolicy: Never
        ports:
        - name: primary-port
          containerPort: 5555
        - name: ssl-port
          containerPort: 5543
        - name: diagnostic-port
          containerPort: 9999
        resources:
          requests:
            cpu: "0.5"
            memory: "0.5Gi"
          limits:
            cpu: "1"
            memory: "1.5Gi"
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /invoke/wm.server/ping
            port: 5555
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 5
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /invoke/wm.server/ping
            port: 5555
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 5
        volumeMounts:
        - name: msr-license
          mountPath: /opt/softwareag/IntegrationServer/config/licenseKey.xml
          subPath: msr-licensekey.xml
          readOnly: false
        - name: tsa-license
          mountPath: /opt/softwareag/common/conf/terracotta-license.key
          subPath: terracotta-license.key
          readOnly: false
        - name: setenv
          mountPath: /opt/softwareag/IntegrationServer/bin/setenv.sh
          subPath: setenv.sh
          readOnly: false
        - name: app-prop
          mountPath: /opt/softwareag/IntegrationServer/application.properties
          subPath: application.properties
          readOnly: false
        - name: jndi-prop
          mountPath: /tmp/jndi_DEFAULT_IS_JNDI_PROVIDER.properties
          subPath: jndi_DEFAULT_IS_JNDI_PROVIDER.properties
          readOnly: false
        - name: messaging-prop
          mountPath: /tmp/messaging.cnf
          subPath: messaging.cnf
          readOnly: false
        - name: jms-prop
          mountPath: /tmp/jms.cnf
          subPath: jms.cnf
          readOnly: false
        - name: default-keystore
          mountPath: /tmp/keystore.jks
          subPath: keystore.jks
          readOnly: false
        - name: default-truststore
          mountPath: /tmp/truststore.jks
          subPath: truststore.jks
        - name: integration-server-logs
          mountPath: /opt/softwareag/IntegrationServer/logs/
          readOnly: false
        command:
        - /bin/sh
        - -c
        - |
         cp /tmp/keystore.jks   /opt/softwareag/common/conf/keystore.jks
         cp /tmp/truststore.jks /opt/softwareag/common/conf/truststore.jks
         cp /tmp/jndi_DEFAULT_IS_JNDI_PROVIDER.properties  /opt/softwareag/IntegrationServer/config/jndi/jndi_DEFAULT_IS_JNDI_PROVIDER.properties
         cp /tmp/messaging.cnf /opt/softwareag/IntegrationServer/config/messaging.cnf
         cp /tmp/jms.cnf  /opt/softwareag/IntegrationServer/config/jms.cnf
         /opt/softwareag/IntegrationServer/bin/startContainer.sh
      volumes:
      - name: msr-license
        configMap:
          name: idbi-apim-ismsr-license-config
          items:
          - key: msr-licensekey.xml
            path: msr-licensekey.xml
          defaultMode: 0777
      - name: tsa-license
        configMap:
          name: idbi-apim-ismsr-license-config
          items:
          - key: terracotta-license.key
            path: terracotta-license.key
          defaultMode: 0777
      - name: app-prop
        configMap:
          name: idbi-apim-msr2-config
          items:
          - key: application.properties
            path: application.properties
          defaultMode: 0777
      - name: jndi-prop
        configMap:
          name: idbi-apim-msr2-config
          items:
          - key: jndi_DEFAULT_IS_JNDI_PROVIDER.properties
            path: jndi_DEFAULT_IS_JNDI_PROVIDER.properties
          defaultMode: 0777
      - name: messaging-prop
        configMap:
          name: idbi-apim-msr2-config
          items:
          - key: messaging.cnf
            path: messaging.cnf
          defaultMode: 0777
      - name: jms-prop
        configMap:
          name: idbi-apim-msr2-config
          items:
          - key: jms.cnf
            path: jms.cnf
          defaultMode: 0777
      - name: setenv
        configMap:
          name: idbi-apim-msr2-config
          items:
          - key: setenv.sh
            path: setenv.sh
          defaultMode: 0777
      -  name: default-keystore
         configMap:
          name: idbi-apim-default-keystore-config
          items:
            - key: keystore.jks
              path: keystore.jks
          defaultMode: 0777      
      -  name: default-truststore
         configMap:
          name: idbi-apim-default-truststore-config
          items:
            - key: truststore.jks
              path: truststore.jks
          defaultMode: 0777
      - name: integration-server-logs
        hostPath:
             path: /data/msr1/is-logs
             type: DirectoryOrCreate
