apiVersion: v1
kind: Service
metadata:
  name: idbi-apim-tsa-nodeport-svc
  labels:
    app: idbi-apim-tsa-nodeport-svc
  namespace: nsp-idbi-apim-uat
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: idbi-apim-tsa-cluster
  ports:
    - name: server
      port: 9510
      targetPort: 9510
      nodePort: 30050
    - name: replication
      port: 9530
      targetPort: 9530
      nodePort: 30051
    - name: management
      port: 9540
      targetPort: 9540
      nodePort: 30052
