apiVersion: v1
kind: ConfigMap
metadata:
  name: idbi-apim-kibana-config
  namespace: nsp-idbi-apim-uat
data:
  kibana.yml: |
    server.port: 5601
    server.host: "0.0.0.0"
    server.basePath: "/apigatewayui/dashboardproxy"
    elasticsearch.hosts: "http://idbi-apim-es-svc-h.nsp-idbi-apim-uat.svc.cluster.local:9200"
    kibana.index: "gateway_default_dashboard"
    elasticsearch.requestTimeout: 90000
    pid.file: kibana.pid
    console.enabled: false
    telemetry.enabled: false



