---
apiVersion: v1
kind: Service
metadata:
  name: idbi-apim-mws-nodeport-svc
  labels:
    app: idbi-apim-mws-nodeport-svc
  namespace: nsp-idbi-apim-uat
spec:
  type: NodePort
  selector:
    app: idbi-apim-mws-node
  ports:
  - name: mws-https-nodeport
    port: 8585
    targetPort: 8585
    nodePort: 30025
---
apiVersion: v1
kind: Service
metadata:
  name: idbi-apim-mws-svc-h
  labels:
    app: idbi-apim-mws-svc-h
  namespace: nsp-idbi-apim-uat
spec:
  clusterIP: None
  selector:
    app: idbi-apim-mws-node
  ports:
  - name: mws-https-port
    port: 8585
