apiVersion: v1
kind: ConfigMap
metadata:
  name: idbi-apim-apigw-config
  namespace: nsp-idbi-apim-uat
data:

  application.properties: |
    #Sample Generated Template
    #Fri Oct 08 10:30:28 IST 2021
    jdbc.ISInternal.dbURL=jdbc\:wm\:oracle\://dcoradbnpscan.idbibank.com\:15210;serviceName\=APIMUATSRV
    jdbc.ISInternal.password={AES}JQmFz1BhOkxdpO1bxrlTHQ==
    jdbc.ISInternal.userid=apigwuat
    jdbc.MWSUser.dbURL=jdbc\:wm\:oracle\://dcoradbnpscan.idbibank.com\:15210;serviceName\=APIMUATSRV
    jdbc.MWSUser.password={AES}2txKs7gKqS5e4YKVYRyCFA==
    jdbc.MWSUser.userid=mwsuat
    settings.watt.server.cluster.aware=true
    settings.watt.server.cluster.name=APIGatewayTSACluster
    settings.watt.server.cluster.tsaURLs=idbi-apim-tsa-cluster-0.idbi-apim-tsa-svc-h.nsp-idbi-apim-uat.svc.cluster.local\:9510,idbi-apim-tsa-cluster-1.idbi-apim-tsa-svc-h.nsp-idbi-apim-uat.svc.cluster.local\:9510
    settings.watt.server.compile=/opt/softwareag/jvm/jvm/bin/javac -classpath {0} -d {1} {2}
    settings.watt.server.auth.samlResolver=https://idbi-apim-mws-svc-h.nsp-idbi-apim-uat.svc.cluster.local:8585/services/SAML
    settings.watt.server.threadPool=1000
    settings.watt.net.jsse.client.disabledProtocols=SSLv2Hello,SSLv3,TLSv1,TLSv1.1
    settings.watt.net.jsse.server.disabledProtocols=SSLv2Hello,SSLv3,TLSv1,TLSv1.1
    user.Administrator.password={AES}/Rr3q6B6LfFEOShP9FJ0jUwbvqGC7rAKwvzC3kkMgEg=
    user.Developer.password={AES}/Rr3q6B6LfFEOShP9FJ0jUwbvqGC7rAKwvzC3kkMgEg=
    user.Replicator.password={AES}/Rr3q6B6LfFEOShP9FJ0jUwbvqGC7rAKwvzC3kkMgEg=
    truststore.DEFAULT_JVM_TRUSTSTORE.ksLocation=/opt/softwareag/jvm/jvm/jre/lib/security/cacerts
    truststore.DEFAULT_JVM_TRUSTSTORE.ksPassword={AES}z/+xVlzI9T/Dfo7Su4lrCQ==
    keystore.IDBI_Keystore.keyAlias.idbibank.keyAliasPassword={AES}KWbniYeILIJ4Cphs7Tdm91kTBR6t5rVRVLZ0cyiJ20U=
    keystore.IDBI_Keystore.ksLocation=/opt/softwareag/common/conf/IDBI_Keystore/keystore.jks
    keystore.IDBI_Keystore.ksPassword={AES}KWbniYeILIJ4Cphs7Tdm91kTBR6t5rVRVLZ0cyiJ20U=
    truststore.IDBI_Truststore.ksLocation=/opt/softwareag/common/conf/IDBI_Truststore/truststore.jks
    truststore.IDBI_Truststore.ksPassword={AES}O1e2whkLOxlv+xDIMJZgBR/jpQWQJz0gfdRTe9QUnPE=
    truststore.istruststore.ksLocation=/opt/softwareag/common/conf/IDBI_Truststore/truststore.jks
    truststore.istruststore.ksPassword={AES}O1e2whkLOxlv+xDIMJZgBR/jpQWQJz0gfdRTe9QUnPE=
    keystore.iskeystore.keyAlias.idbibank.keyAliasPassword={AES}KWbniYeILIJ4Cphs7Tdm91kTBR6t5rVRVLZ0cyiJ20U=
    keystore.iskeystore.ksLocation=/opt/softwareag/common/conf/IDBI_Keystore/keystore.jks
    keystore.iskeystore.ksPassword={AES}KWbniYeILIJ4Cphs7Tdm91kTBR6t5rVRVLZ0cyiJ20U=

  custom_wrapper.conf:  |
    #encoding=UTF-8
    wrapper.app.parameter.2=4
    wrapper.app.parameter.5=-service
    wrapper.app.parameter.6=sagis107
    wrapper.java.additional.100=-server
    wrapper.java.additional.101=-Dorg.apache.xml.dtm.DTMManager=org.apache.xml.dtm.ref.DTMManagerDefault
    wrapper.java.additional.102=-Djavax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom=com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl
    wrapper.java.additional.103=-Dcom.webmethods.sc.auditing.Use80TableFormat=true
    wrapper.java.additional.104=-Dsun.lang.ClassLoader.allowArraySyntax=true
    wrapper.java.additional.105=-XX:+UseOpenJSSE
    wrapper.java.additional.201=-DWM_HOME=/opt/softwareag
    wrapper.java.additional.202=-Dwatt.server.prepend.classes=/opt/softwareag/common/lib/wm-converters.jar
    wrapper.java.additional.203=-Dwatt.server.append.classes=
    wrapper.java.additional.204=-Dlog4j.configurationFile="/opt/softwareag/profiles/IS_default/configuration/logging/log4j2.properties,.tc.custom.log4j2.properties"
    wrapper.java.additional.204.stripquotes=TRUE
    wrapper.java.additional.301=-Dorg.tanukisoftware.wrapper.WrapperStartStopApp.passthroughMode=START
    wrapper.java.additional.302=-Djava.awt.headless=true
    wrapper.java.additional.303=-DLog4jContextSelector=org.apache.logging.log4j.core.selector.BasicContextSelector
    wrapper.java.classpath.3=/opt/softwareag/common/lib/wm-converters.jar
    wrapper.java.initmemory=4096
    wrapper.java.library.path.11=/opt/softwareag/IntegrationServer/instances/default/lib
    wrapper.java.library.path.append_system_path=TRUE
    wrapper.java.maxmemory=4096
    wrapper.jvm_exit.timeout=300
    wrapper.on_exit.42=RESTART
    wrapper.ping.timeout=300
    wrapper.restart.reload_configuration=TRUE
    wrapper.shutdown.timeout=300
    wrapper.single_invocation=TRUE
    wrapper.working.dir=/opt/softwareag/IntegrationServer/instances/default
    wrapper.java.additional.106=-Djava.security.properties=config/security/webm_override_java.security
    wrapper.java.additional.999=-Dtest.cluster.withDerby=true

  com.softwareag.catalina.connector.https.pid-apigateway.properties: |
    ##
    #Tue Nov 02 22:32:11 IST 2021
    clientAuth=false
    sslProtocol=TLS
    SSLEnabled=true
    keystoreFile=/opt/softwareag/profiles/IS_default/configuration/tomcat/conf/keystore.jks
    enabled=true
    port=9072
    scheme=https
    enableLookups=false
    @secure.keystorePass=!dbi3ank@U@T!Certs
    secure=true
    maxSpareThreads=75
    alias=defaultHttps
    maxThreads=150
    keystoreType=JKS
    server=SoftwareAG-Runtime
    disableUploadTimeout=true
    description=Default HTTPS Connector
    algorithm=SunX509
    minSpareThreads=25
    acceptCount=100
    maxHttpHeaderSize=8192


  config-sources.yml: |
    ######################## Master configuration ############################
    #
    # This is the master configuration file which contains the configuration 
    # source definitions.
    #
    # You can find the full configuration reference here:
    # http://techcommunity.softwareag.com/pwiki/-/wiki/Main/Starting+API+Gateway+using+externalized+configurations
    #
    #=======================  Sources configuration ==========================

    sources:
    - type: YAML
      allowEdit: true
      properties:
        #Provide the appropriate filename
        location: /opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration/system-settings.yml

  system-settings.yml: |
    ---
    apigw:
      elasticsearch:
        tenantId: default
        hosts: idbi-apim-es-svc-h.nsp-idbi-apim-uat.svc.cluster.local:9200
        autostart: false
        http:
          keepAlive: true
          keepAliveMaxConnections: 50
          keepAliveMaxConnectionsPerRoute: 15
          connectionTimeout: 10000
          socketTimeout: 30000
          maxRetryTimeout: 100000
        https:
          enabled: false
        sniff:
          enable: true
          timeInterval: 60000
        clientHttpResponseSize: 100
      kibana:
        dashboardInstance: http://idbi-apim-kibana-svc.nsp-idbi-apim-uat.svc.cluster.local:5601
        autostart: false