apiVersion: apps/v1
kind: Deployment
metadata: 
  name: idbi-apim-apigw-deploy
  labels:
    app: idbi-apim-apigw-deploy
  namespace: nsp-idbi-apim-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idbi-apim-apigw-cluster
  template:
    metadata:
      labels:
        app: idbi-apim-apigw-cluster
    spec:
      # hostAliases:
      # - ip: "10.142.15.245"
      #   hostnames:
      #   - "dcapiporpr01"
      terminationGracePeriodSeconds: 60
      affinity:
        # Pods will be placed in the worker node that has the label terracotta-node=terracotta
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: apigateway-node-uat
                operator: In
                values:
                - "apigateway"
        # Pods will label app=idbi-apim-tsa-cluster will not be placed together
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - idbi-apim-apigw-cluster
              topologyKey: "kubernetes.io/hostname"
      # Toleration condition for Pods when the node is tainted and the subsequent effect
      tolerations:
      - key: "node-role.kubernetes.io/apigateway-uat"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: idbi-apim-apigw-server
        image: 10.143.140.124:5010/apim-sag-apigw-ext:v1.4
        # imagePullPolicy: Never
        ports:
        - name: is-port
          containerPort: 5555
        - name: comm-port
          containerPort: 5543
        - name: apigw-port
          containerPort: 9072
        - name: diagnostic-port
          containerPort: 9999
        resources:
          requests:
            cpu: "0.25"
            memory: "4Gi"
          limits:
            cpu: "1.5"
            memory: "6Gi"
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /invoke/wm.server/ping
            port: 5555
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 5
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /invoke/wm.server/ping
            port: 5555
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 5
        volumeMounts:
        - name: apigw-license
          mountPath: /opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml
          subPath: apigw-licensekey.xml
          readOnly: false
        - name: tsa-license
          mountPath: /opt/softwareag/common/conf/terracotta-license.key
          subPath: terracotta-license.key
          readOnly: false
        - name: custom-wrapper
          mountPath: /opt/softwareag/profiles/IS_default/configuration/custom_wrapper.conf
          subPath: custom_wrapper.conf
          readOnly: false
        - name: app-prop
          mountPath: /opt/softwareag/IntegrationServer/application.properties
          subPath: application.properties
          readOnly: false
        - name: apigw-ui-https
          mountPath: /tmp/com.softwareag.catalina.connector.https.pid-apigateway.properties
          subPath: com.softwareag.catalina.connector.https.pid-apigateway.properties
          readOnly: false
        - name: config-sources
          mountPath: /tmp/config-sources.yml
          subPath: config-sources.yml
          readOnly: false
        - name: system-settings
          mountPath: /tmp/system-settings.yml
          subPath: system-settings.yml
          readOnly: false
        - name: default-keystore
          mountPath: /tmp/keystore.jks
          subPath: keystore.jks
          readOnly: false
        - name: default-truststore
          mountPath: /tmp/truststore.jks
          subPath: truststore.jks
        - name: integration-server-logs
          mountPath: /opt/softwareag/IntegrationServer/instances/default/logs/
          readOnly: false
        # - name: integration-server-packages
        #   mountPath: /opt/softwareag/IntegrationServer/instances/default/packages/
        #   readOnly: false
        - name: profile-logs
          mountPath: /opt/softwareag/profiles/IS_default/logs/
          readOnly: false
        command:
        - /bin/sh
        - -c
        - |
          cp /tmp/keystore.jks   /opt/softwareag/common/conf/IDBI_Keystore/keystore.jks
          cp /tmp/truststore.jks /opt/softwareag/common/conf/IDBI_Truststore/truststore.jks
          cp /tmp/keystore.jks   /opt/softwareag/profiles/IS_default/configuration/tomcat/conf/keystore.jks
          cp /tmp/com.softwareag.catalina.connector.https.pid-apigateway.properties /opt/softwareag/profiles/IS_default/configuration/com.softwareag.platform.config.propsloader/com.softwareag.catalina.connector.https.pid-apigateway.properties
          cp /tmp/config-sources.yml /opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration/config-sources.yml
          cp /tmp/system-settings.yml /opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration/system-settings.yml
          /opt/softwareag/IntegrationServer/bin/startContainer.sh
      volumes:
      - name: apigw-license
        configMap:
          name: idbi-apim-apigw-license-config
          items:
          - key: apigw-licensekey.xml
            path: apigw-licensekey.xml
          defaultMode: 0777
      - name: tsa-license
        configMap:
          name: idbi-apim-apigw-license-config
          items:
          - key: terracotta-license.key
            path: terracotta-license.key
          defaultMode: 0777
      - name: custom-wrapper
        configMap:
          name: idbi-apim-apigw-config
          items:
          - key: custom_wrapper.conf
            path: custom_wrapper.conf
          defaultMode: 0777
      - name: app-prop
        configMap:
          name: idbi-apim-apigw-config
          items:
          - key: application.properties
            path: application.properties
          defaultMode: 0777
      - name: apigw-ui-https
        configMap:
          name: idbi-apim-apigw-config
          items:
          - key: com.softwareag.catalina.connector.https.pid-apigateway.properties
            path: com.softwareag.catalina.connector.https.pid-apigateway.properties
          defaultMode: 0777
      - name: config-sources
        configMap:
          name: idbi-apim-apigw-config
          items:
          - key: config-sources.yml
            path: config-sources.yml
          defaultMode: 0777
      - name: system-settings
        configMap:
          name: idbi-apim-apigw-config
          items:
          - key: system-settings.yml
            path: system-settings.yml
          defaultMode: 0777
      -  name: default-keystore
         configMap:
          name: idbi-apim-default-keystore-config
          items:
          - key: keystore.jks
            path: keystore.jks
          defaultMode: 0777      
      -  name: default-truststore
         configMap:
          name: idbi-apim-default-truststore-config
          items:
          - key: truststore.jks
            path: truststore.jks
          defaultMode: 0777
      - name: integration-server-logs
        hostPath:
          path: /data/apigw/is-logs
          type: DirectoryOrCreate
      # - name: integration-server-packages
      #   hostPath:
      #     path: /data/apigw/is-packages
      #     type: DirectoryOrCreate
      - name: profile-logs
        hostPath:
          path: /data/apigw/is-profile-logs
          type: DirectoryOrCreate