apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage-efk-elastic
  namespace: idbi-efk
provisioner: kubernetes/nfs
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"
